GET http://localhost:3001/api/files
auth_token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1leWF6aGFnYW4ub2ZjbEBnbWFpbC5jb20iLCJpZCI6IjYxYjM3ZTRmMTNkOTc4YjU3OGJmMTg4NiIsInByb2Nlc3MiOiJsb2dpbiIsImlhdCI6MTYzOTIwNDM5MywiZXhwIjoxNjM5MjkwNzkzfQ.mwcckomT7jyQ-jETYBct6y6Wsu7FDp8s8PvLFheI9KE
